export const apps = [
    {
        PK: 'IDMS',
        AssignmentGroup: 'Dig-AMS-EIS',
        AwsAccounts: '',
        CINumber: 'CI00030593',
        ContactEmail: 'DWAYNE.DOHERTY@woodside.com',
        CostCode: 'P0-000085-7A-1-01-E04',
        LastModified: '2023-03-02T07:52:16.820Z',
        Name: 'Bentley IDMS',
        Owner: 'Dwayne Doherty',
        OwnerRole: 'Event.User.IDMS',
        ShortName: 'IDMS',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'IPS',
        AssignmentGroup: 'Dig-Identity and Access Mgmt',
        AwsAccounts: '',
        CINumber: 'SNSVC0001668',
        ContactEmail: 'LUKE.OUTRAM@WOODSIDE.COM.AU',
        CostCode: 'AU30000239',
        LastModified: '2023-02-14T06:08:42.424Z',
        Name: 'Identity Profile Store',
        Owner: 'Luke Outram',
        OwnerRole: 'Event.User.IPS',
        ShortName: 'IPS',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'ART',
        AssignmentGroup: 'Dig-ART',
        AwsAccounts: '',
        CINumber: 'APM0001471',
        ContactEmail: 'ADAM.FERGUSON@WOODSIDE.COM.AU',
        CostCode: 'P0-000286-0A-4-05-003',
        LastModified: '2023-02-14T06:08:42.799Z',
        Name: 'Sentient',
        Owner: 'Adam Ferguson',
        OwnerRole: 'Event.User.ART',
        ShortName: 'ART',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'WILLOW',
        AssignmentGroup: 'Dig-AMS-Corp',
        AwsAccounts: '',
        CINumber: 'CI00031099',
        ContactEmail: 'Sepideh.Zarkoob@woodside.com.au',
        CostCode: 'AU30000066',
        LastModified: '2023-02-14T06:08:43.298Z',
        Name: 'Willow',
        Owner: 'Sepideh Zarkoob',
        OwnerRole: 'Event.User.WILLOW',
        ShortName: 'WILLOW',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'SENTIENT',
        AssignmentGroup: 'Dig-ART',
        AwsAccounts: '',
        CINumber: 'APM0001471',
        ContactEmail: "'-",
        CostCode: 'P0-000286',
        LastModified: '2023-02-09T01:50:45.260Z',
        Name: 'Sentient',
        Owner: 'Adam Ferguson',
        OwnerRole: 'Event.User.Sentient',
        ShortName: 'SENTIENT',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'VPOB',
        AssignmentGroup: 'Dig-AMS-Corp',
        AwsAccounts: '',
        CINumber: 'CI00030351',
        ContactEmail: 'BRIAN.STUART@woodside.com.au',
        CostCode: 'AU30000239',
        LastModified: '2023-02-14T06:08:43.588Z',
        Name: 'Vantage Personnel on Board',
        Owner: 'Brian Stuart',
        OwnerRole: 'Event.User.VPOB',
        ShortName: 'VPOB',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'JIRA',
        AssignmentGroup: 'Dig-Jira/Confluence Support',
        AwsAccounts: '',
        CINumber: 'CI00030321',
        ContactEmail: 'NOELENE.CLARKE@WOODSIDE.COM.AU',
        CostCode: "'-",
        LastModified: '2023-02-14T06:08:43.850Z',
        Name: 'JIRA Data Center',
        Owner: 'Noelene Clarke',
        OwnerRole: 'Event.User.JIRA',
        ShortName: 'JIRA',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'PWRPLT',
        AssignmentGroup: 'Dig-Power Platform',
        AwsAccounts: '{"NP":{"M":{"Name":{"S":"-"}}},"PRD":{"M":{"Name":{"S":"-"}}}}',
        CINumber: 'APM0002129',
        ContactEmail: 'ANTHONY.TEO@WOODSIDE.COM.AU',
        CostCode: "'-",
        LastModified: '2023-02-28T00:51:46.107Z',
        Name: 'Power Platform',
        Owner: 'Anthony Teo',
        OwnerRole: 'Event.User.PWRPLT',
        ShortName: 'PWRPLT',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'CBM',
        AssignmentGroup: 'Dig-CBM Squad',
        AwsAccounts: '',
        CINumber: 'CI00063903',
        ContactEmail: 'GLYNN.DAVIES@WOODSIDE.COM.AU',
        CostCode: "'-",
        LastModified: '2023-02-14T06:08:44.181Z',
        Name: 'Conditional Based Maintenance',
        Owner: 'Glynn Davies',
        OwnerRole: 'Event.User.CBM',
        ShortName: 'CBM',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'HYPAUT',
        AssignmentGroup: '',
        AwsAccounts: '',
        CINumber: 'APM0002489',
        ContactEmail: "'-",
        CostCode: 'AU30000066',
        LastModified: '23/8/2022',
        Name: 'HyperAutomation',
        Owner: 'Nick Bower',
        OwnerRole: 'Event.User.HYPAUT',
        ShortName: 'HYPAUT',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'SAR',
        AssignmentGroup: 'Dig-AMS-Corp',
        AwsAccounts: '',
        CINumber: 'APM0001989',
        ContactEmail: 'ONKAR.NAVEKAR@woodside.com',
        CostCode: "'-",
        LastModified: '2023-02-14T06:08:44.488Z',
        Name: 'Site Access Requests',
        Owner: 'Natalie Sermon',
        OwnerRole: 'Event.User.SAR',
        ShortName: 'SAR',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'SAP',
        AssignmentGroup: 'Dig-ERP-Netweaver',
        AwsAccounts: '',
        CINumber: 'CI00030169',
        ContactEmail: "'-",
        CostCode: "'-",
        LastModified: '2023-02-14T06:08:44.883Z',
        Name: 'SAP ERP',
        Owner: 'Jimmy Goda',
        OwnerRole: 'Event.User.SAP',
        ShortName: 'SAP',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'IE',
        AssignmentGroup: '',
        AwsAccounts: '',
        CINumber: 'APM0002413',
        ContactEmail: 'Shaun Clements <shaun.clements@woodside.com.au>',
        CostCode: 'P0-000286-0A-4-02-006',
        LastModified: '2023-01-30T05:47:26Z',
        Name: 'Intelligent Execution',
        Owner: 'Peter Watkins',
        OwnerRole: 'Event.User.IE',
        ShortName: 'IE',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'ISSOW',
        AssignmentGroup: 'Dig-AMS-EIS',
        AwsAccounts: '',
        CINumber: 'CI00030341',
        ContactEmail: "'-",
        CostCode: "'-",
        LastModified: '2023-02-14T06:08:45.513Z',
        Name: 'ISSOW',
        Owner: 'Gary Sargeson',
        OwnerRole: 'Event.User.ISSOW',
        ShortName: 'ISSOW',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'PRM',
        AssignmentGroup: '',
        AwsAccounts: '',
        CINumber: 'CI000XXXX',
        ContactEmail: "'-",
        CostCode: "'-",
        LastModified: '23/8/2022',
        Name: 'PRM',
        Owner: 'Michael Richards',
        OwnerRole: 'Event.User.PRM',
        ShortName: 'PRM',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'FUSE',
        AssignmentGroup: 'Dig-Fuse',
        AwsAccounts: '',
        CINumber: 'CI00064884',
        ContactEmail: 'nick.bower@woodside.com.au',
        CostCode: 'P0-000283-1A-1-10',
        LastModified: '2023-02-14T06:08:45.768Z',
        Name: 'FUSE',
        Owner: 'Nick Bower',
        OwnerRole: 'Event.User.FUSE',
        ShortName: 'FUSE',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
    {
        PK: 'PRISM',
        AssignmentGroup: 'DIG-PRISM',
        AwsAccounts: '',
        CINumber: 'APM0001112',
        ContactEmail: "'-",
        CostCode: 'P0-000238-0A-4-03-003',
        LastModified: '2023-02-14T06:08:46.026Z',
        Name: 'PRISM',
        Owner: 'Michael Richards',
        OwnerRole: 'Event.User.PRISM',
        ShortName: 'PRISM',
        SupportEmail: '[{"S":"james.vandeven@woodside.com.au"}]',
    },
];
