name: 'Deploying to DEV & QA'

on:
  push:
    branches:
      - main

jobs:
  check-codebase:
    name: Check Codebase
    uses: ./.github/workflows/check-codebase.yaml
    with:
      isFeatureBranch: false
      nxBaseCommit: main~1
      nxHeadCommit: main

  build:
    name: Build and Install Dependencies
    runs-on: ubuntu-latest
    needs: [check-codebase]

    steps:
      # checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PNPMv8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NodeJs v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm config set "@woodside:registry" https://npm.pkg.github.com
          pnpm install --frozen-lockfile

      # Build the API and Docs once here as there is no env specific build config
      - name: Build API Application
        run: pnpm build:api:prod

      - name: Build Docs Application
        run: pnpm build:docs

      # Upload the API build to be used in subsequent deployments
      - name: Update artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-api
          path: dist/apps/api

      # Upload the API build to be used in subsequent deployments
      - name: Update artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-docs
          path: dist/apps/docs

  stack-dev-all:
    name: Deploy NP & PRD Broker, EventApi and SchemaRegistry stacks for DEV
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 727026770742
      CDK_STAGE: DEV

    # REQUIRED - Please do not remove.
    permissions:
      id-token: write
      contents: write

    steps:
      # checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PNPMv8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NodeJs v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install ESBuild, CDK and TSNode
        run: npm install -g aws-cdk esbuild ts-node

      - name: Install Dependencies
        run: |
          pnpm config set "@woodside:registry" https://npm.pkg.github.com
          pnpm install --frozen-lockfile

      # should this be npm ci?
      - name: Install AWS SDK Layer Packages
        working-directory: apps/infrastructure/resources/lambda-layers/aws-sdk/nodejs
        run: npm install
      - name: Install NestJS Layer Packages
        working-directory: apps/infrastructure/resources/lambda-layers/nestjs/nodejs
        run: npm install

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-api
          path: dist/apps/api

      # REQUIRED - Assume deployment role
      - name: Assume deployment role
        uses:  Woodside/assume-deployment-role@v1
        with:
          deployment-role-name: eai-event-integration-platform-dev-GitHubDeploymentRole
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Deploy CDK
        working-directory: apps/infrastructure
        run: cdk deploy --all --ci --context stage="${{ env.CDK_STAGE }}" --require-approval never --force true

  integration-hub-dev:
    name: Deploy Dev IntegrationHub
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 727026770742
      BUCKET: s3://arn:aws:s3:ap-southeast-2:278364088108:accesspoint/c775fc6a-7a91-45c9-b161-2707c2ab473b/integration-dev.dev.app.woodside

    # REQUIRED - Please do not remove.
    permissions:
      id-token: write
      contents: write

    steps:
      # checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NodeJs v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm config set "@woodside:registry" https://npm.pkg.github.com
          pnpm install --frozen-lockfile

      # Copy Environments File
      - name: Copy Dev Environments File
        run: |
          echo "Copying environment.dev.ts as the base environments file"
          cp ./apps/integration-hub/src/environments/environment.dev.ts ./apps/integration-hub/src/environments/environment.ts

      - name: Build Event IntegrationHub
        run: |
          pnpm build:ui:dev
          cp ./ci/env.dev.js ./dist/apps/integration-hub/env.js
          cp ./ci/app.config.json ./dist/apps/integration-hub/app.config.json

      - name: Download Docs from artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-docs
          path: dist/apps/integration-hub/docs

      # REQUIRED - Assume deployment role
      - name: Assume deployment role
        uses:  Woodside/assume-deployment-role@v1
        with:
          deployment-role-name: eai-event-integration-platform-dev-GitHubDeploymentRole
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Deploy Dev Event IntegrationHub
        run: |
          cd ./dist/apps/integration-hub
          aws s3 sync . ${{ env.BUCKET }} --delete --acl bucket-owner-full-control --cache-control 'max-age=3600' \
             --exclude 'index.html' \
             --exclude 'docs/index.html' \
             --exclude 'env.js' \
             --exclude 'app.config.json'
          aws s3 cp index.html ${{ env.BUCKET }}/index.html --acl bucket-owner-full-control --cache-control no-cache
          aws s3 cp docs/index.html ${{ env.BUCKET }}/docs/index.html --acl bucket-owner-full-control --cache-control no-cache
          aws s3 cp env.js ${{ env.BUCKET }}/env.js --acl bucket-owner-full-control --cache-control no-store
          aws s3 cp app.config.json ${{ env.BUCKET }}/app.config.json --acl bucket-owner-full-control --cache-control no-store

  stack-qa-np:
    name: Deploy NP Broker stack for QA
    runs-on: ubuntu-latest
    needs: [build]
    environment: qa
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 727026770742
      CDK_STAGE: QA

    # REQUIRED - Please do not remove.
    permissions:
      id-token: write
      contents: write

    steps:
      # checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NodeJs v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install ESBuild, CDK and TSNode
        run: npm install -g aws-cdk esbuild ts-node

      - name: Install Dependencies
        run: |
          pnpm config set "@woodside:registry" https://npm.pkg.github.com
          pnpm install --frozen-lockfile

      # should this be npm ci?
      - name: Install AWS SDK Layer Packages
        working-directory: apps/infrastructure/resources/lambda-layers/aws-sdk/nodejs
        run: npm install
      - name: Install NestJS Layer Packages
        working-directory: apps/infrastructure/resources/lambda-layers/nestjs/nodejs
        run: npm install

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-api
          path: dist/apps/api

      # REQUIRED - Assume deployment role
      - name: Assume deployment role
        uses:  Woodside/assume-deployment-role@v1
        with:
          deployment-role-name: eai-event-integration-platform-qa-GitHubDeploymentRole
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Deploy CDK
        working-directory: apps/infrastructure
        run: cdk deploy EventBrokerStackNp --ci --context stage="${{ env.CDK_STAGE }}" --require-approval never --force true

  stack-qa-prd:
    name: Deploy PRD Broker, EventApi and SchemaRegistry stacks for QA
    runs-on: ubuntu-latest
    needs: [build]
    environment: qa
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 144028967590
      CDK_STAGE: QA

    # REQUIRED - Please do not remove.
    permissions:
      id-token: write
      contents: write

    steps:
      # checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NodeJs v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install ESBuild, CDK and TSNode
        run: npm install -g aws-cdk esbuild ts-node

      - name: Install Dependencies
        run: |
          pnpm config set "@woodside:registry" https://npm.pkg.github.com
          pnpm install --frozen-lockfile

      # should this be npm ci?
      - name: Install AWS SDK Layer Packages
        working-directory: apps/infrastructure/resources/lambda-layers/aws-sdk/nodejs
        run: npm install
      - name: Install NestJS Layer Packages
        working-directory: apps/infrastructure/resources/lambda-layers/nestjs/nodejs
        run: npm install

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-api
          path: dist/apps/api

      # REQUIRED - Assume deployment role
      - name: Assume deployment role
        uses:  Woodside/assume-deployment-role@v1
        with:
          deployment-role-name: eai-event-integration-platform-qa-GitHubDeploymentRole
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Deploy CDK
        working-directory: apps/infrastructure
        run: cdk deploy EventBrokerStack SchemaRegistryStack EventApiStack EventCustomerApiStack --ci --context stage="${{ env.CDK_STAGE }}" --require-approval never --force true

  integration-hub-qa:
    name: Deploy QA IntegrationHub
    runs-on: ubuntu-latest
    needs: [build]
    environment: qa
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: 727026770742
      BUCKET: s3://arn:aws:s3:ap-southeast-2:278364088108:accesspoint/ccdc3569-f743-47e1-863f-ee29959725b6/integration-qa.dev.app.woodside

    # REQUIRED - Please do not remove.
    permissions:
      id-token: write
      contents: write

    steps:
      # checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm config set "@woodside:registry" https://npm.pkg.github.com
          pnpm install --frozen-lockfile

      # Copy Environments File
      - name: Copy Environments File
        run: |
          echo "Copying environment.qa.ts as the base environments file"
          cp ./apps/integration-hub/src/environments/environment.qa.ts ./apps/integration-hub/src/environments/environment.ts

      - name: Build Event IntegrationHub
        run: |
          pnpm build:ui:qa
          cp ./ci/env.qa.js ./dist/apps/integration-hub/env.js
          cp ./ci/app.config.json ./dist/apps/integration-hub/app.config.json

      - name: Download Docs from artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-docs
          path: dist/apps/integration-hub/docs

      # REQUIRED - Assume deployment role
      - name: Assume deployment role
        uses:  Woodside/assume-deployment-role@v1
        with:
          deployment-role-name: eai-event-integration-platform-qa-GitHubDeploymentRole
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Deploy QA Event IntegrationHub
        run: |
          cd ./dist/apps/integration-hub
          aws s3 sync . ${{ env.BUCKET }} --delete --acl bucket-owner-full-control --cache-control 'max-age=3600' \
             --exclude 'index.html' \
             --exclude 'docs/index.html' \
             --exclude 'env.js' \
             --exclude 'app.config.json'
          aws s3 cp index.html ${{ env.BUCKET }}/index.html --acl bucket-owner-full-control --cache-control no-cache
          aws s3 cp docs/index.html ${{ env.BUCKET }}/docs/index.html --acl bucket-owner-full-control --cache-control no-cache
          aws s3 cp env.js ${{ env.BUCKET }}/env.js --acl bucket-owner-full-control --cache-control no-store
          aws s3 cp app.config.json ${{ env.BUCKET }}/app.config.json --acl bucket-owner-full-control --cache-control no-store
