name: Release Drafter
on:
  push:
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-template.yml
          disable-releaser: github.ref != 'refs/heads/main' # only update release when merged to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
